### ISSUE TITLE
Assert in get_MPAs

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/spatialplanr#103]
Assert in get_MPAs only checks for the defaults, not all the possible options. Need to update.

```
all(Status %in% c("Designated", "Established", "Inscribed")),
all(Desig %in% c("National", "Regional", "International", "Not Applicable")),
all(Category %in% c("Ia", "Ib", "II", "III", "IV"))
```

**Comment by KilianGRIHAULTBARREIRO** [comment]
I don't know how to find all the possible values for those 3 variables, unless if I download the whole world (wdpa_fetch(x="global")).
I've added this to help, tell me if it's enough to push or if you had something else in mind :
`splnr_get_MPAs <- function(PlanUnits,
                           Countries,
                           Status = c("Designated", "Established", "Inscribed"),
                           Desig = c("National", "Regional", "International", "Not Applicable"),
                           Category = c("Ia", "Ib", "II", "III", "IV")) {

  assertthat::assert_that(
    inherits(PlanUnits, "sf"),
    is.character(Countries))

  wdpa_data <- Countries %>%
    lapply(wdpar::wdpa_fetch,
           wait = TRUE,
           download_dir = rappdirs::user_data_dir("wdpar"))

  assertthat::assert_that(
    any(Status %in% wdpa_data[[1]][["STATUS"]]),
    any(Desig %in% wdpa_data[[1]][["DESIG_TYPE"]]),
    any(Category %in% wdpa_data[[1]][["IUCN_CAT"]])
  )

  wdpa_data <- wdpa_data %>%
    dplyr::bind_rows() %>%
    dplyr::filter(.data$MARINE > 0) %>%
    dplyr::filter(.data$IUCN_CAT %in% Category) %>% # filter category
    dplyr::filter(.data$DESIG_TYPE %in% Desig) %>% # filter designation
    dplyr::filter(.data$STATUS %in% Status) %>% # filter status
    wdpar::wdpa_clean(retain_status = NULL, erase_overlaps = FALSE) %>% # clean protected area data
    wdpar::wdpa_dissolve() %>% # Dissolve data to remove overlapping areas.
    dplyr::select("geometry") %>%
    dplyr::mutate(wdpa = 1) %>%
    splnr_convert_toPUs(PlanUnits)

  return(wdpa_data)
}`

**Comment by jaseeverett** [comment]
Sorry. I didn't intend for you to do this. 
If you want to finish it, the options are all in the documentation. 
See Table3.1 in  https://wdpa.s3-eu-west-1.amazonaws.com/WDPA_Manual/English/WDPA_WDOECM_Manual_1_6.pdf
