### ISSUE TITLE
Installing spatialplanr

### ISSUE THREAD

**Issue by SnBuenafe** [MathMarEcol/spatialplanr#11]
Error when installing the package:
`Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/MathMarEcol/spatialplanr/tarball/HEAD' failed`.

Might be related to dependency issues on the following packages: `cmocean`, `nngeo`, `wdpar`, and `mregions`. We were able to solve it by downloading the .zip file, addressing the dependency issues by manually installing these packages in R, and running `install.packages` with the .zip file.

**Comment by tinbuenafe** [comment]
Just an update on this: the `devtools` way of installing it (as per the README.md) works in Mac OS, but not Linux nor Windows.

**Comment by jaseeverett** [comment]
Package has been completely changed so closing this for the moment. We will know soon enough if this is still an issue.
@SnBuenafe Don't install yet. We will let you know when we are ready for testers again
