### ISSUE TITLE
Create function for using IUCN data

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/spatialplanr#4]
It will likely be called `SpatPlan_Get_IUCN`.

I will speak to Tin about how to create this and model in on existing functions

**Comment by jaseeverett** [comment]
We may be able to use https://github.com/RS-eco/rasterSp but it would be good to use the raw polygon data, but to the rasters. We want polygons.

**Comment by tinbuenafe** [comment]
I quickly checked `rasterSp`, and I think that if we want to keep everything in the sf format, we'd probably want to download the raw polygon data as you mentioned. I can't find any automated way to download the IUCN data, and we need an IUCN account to download the files. Do you have an account @jaseeverett or I can create one as well?

**Comment by jaseeverett** [comment]
I spoke to the IUCN and there is no easy way to access the detail. To get bulk data you still need to download for individual groups (mammals, fish, birds etc). 
We are not using Data in this package at the moment so I will close this for the time being. We can come back to it if we reverse course.
