### ISSUE TITLE
Metafunctions

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/spatialplanr#42]
I would like some meta functions to simplify the function names of (for example) `splnr_ClimatePriorityArea`, `splnr_plot_climKernelDensity`, and `splnr_plot_impScore`

We should keep the original functions, but make them internal only. The meta function should then take a variable input of "Ferrier" or "RC' or "RWR" (for example) in the `splnr_plot_impScore` meta function. This will simplify what the user is exposed to - see for example https://mathmarecol.github.io/spatialplanr/reference/index.html where we should keep things as simple as possible so as to not overwhelm the user.

**Comment by sandra-neubert** [comment]
Added metafunctions for climate-smart spatial planning, kernel density plots and importance scores
