### ISSUE TITLE
Splnr_get_boundary "res" parameter in spatialplanr vignette

### ISSUE THREAD

**Issue by KilianGRIHAULTBARREIRO** [MathMarEcol/spatialplanr#76]
The function **splnr_get_boundary** displays the error : "Error in del/by : non-numeric argument to binary operator" when using a custom numeric region, the res parameter needs to be added to fix it. 

``` r
library(spatialplanr) 

Region = c(xmin = 150, xmax = 160, ymin = -40, ymax = -30)
Shape = "Hexagon" 
PU_size = 10000 

cCRS =
  "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs"

Bndry = splnr_get_boundary(Region, Type, cCRS)
#> Error in del/by: argument non numérique pour un opérateur binaire
```

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jaseeverett** [comment]
I'm not sure how your example is working because you haven't got `Type` defined anywhere. Did you clear your workspace before running the code? 

The below code works for me without `res`

``` r
library(spatialplanr) 

Region = c(xmin = 150, xmax = 160, ymin = -40, ymax = -30)
cCRS =
  "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs"
Bndry = splnr_get_boundary(Region, cCRS)

library(ggplot2)
ggplot(data = Bndry) + geom_sf()
```

![](https://i.imgur.com/leKAVx8.png)

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jaseeverett** [comment]
I don't think this is a bug per se, but we do need some better checks on the inputs to all the functions. For example, testing that the input type of `Region` and `cCRS` are of the correct type, and that `Type` exists when it is needed. I will raise a seperate issue for this.

**Comment by KilianGRIHAULTBARREIRO** [comment]
Yes, you are right, I thought the `Type ` was mandatory for any region setting, so we should modify the `splnr_get_boundary` function to ask for the `Type `only when needed. As well as the others as you said, thanks!

**Comment by jaseeverett** [comment]
I agree. Mark it as optional
