### ISSUE TITLE
IUCN status for aquamaps species in spatialplanr vignette

### ISSUE THREAD

**Issue by KilianGRIHAULTBARREIRO** [MathMarEcol/spatialplanr#77]
**IUCN_IA_Targets** object with the **splnr_get_IUCNRedList** function should be separated from its chunk (lines 400-402).

``` r
IUCN_IA_Targets <- Targets %>%
  splnr_get_IUCNRedList(species_col = "Species") %>% # Add RL data to the df
  splnr_targets_byIUCN(IUCN_target = 0.3)
#> Error in Targets %>% splnr_get_IUCNRedList(species_col = "Species") %>% : impossible de trouver la fonction "%>%"
#> Error in Targets %>% splnr_get_IUCNRedList(species_col = "Species") %>% : impossible de trouver la fonction "%>%"
```

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jaseeverett** [comment]
Thanks @KilianGRIHAULTBARREIRO . I agree. Go ahead and move the last 3 lines into a new chunk with `eval=FALSE`. Set the existing chunk to be `eval=TRUE` now
