### ISSUE TITLE
Global Fishing Watch

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/spatialplanr#79]
1. Look into what the global fishing watch data looks like and what is available.
2. Look into the global fishing watch R package.
3. Write a "How To" Rmd file to teach us (Ant's lab) how to use the GFW r package (in a new GitHub repo in MathMarEcol organisation). Use examples from Australia and Micronesia to illustrate how we can use the data. We are particularly interested in flag, location, gear type etc.
4. Write a small introduction to the rmd file explaining how the global fishing watch data is collected. Write some text before each code chunk to explain what the chunk is doing. Explore what the data actually is. Is it gridded, how is it averaged (if at all)?
5. Think about how to incorporate it into spatialplanr as a cost or feature layer 
6. Consider writing a wrapper function to help spatialplanr users use the GFW package - speak to @jaseeverett 
7. If 5 is successful, write a small example in the "cost" section of the spatialplanr vignette

**Comment by jaseeverett** [comment]
A useful paper on GFW https://www.science.org/doi/10.1126/science.aao5646

**Comment by jaseeverett** [comment]
Just moving this discussion from Slack to here. 
We have decided that your `get_gfwData` function is looking really good. We decided that it will not do any regridding of the data as many users will not want this. We will do the regridding with the `spatialgridr` package.

**Comment by jaseeverett** [comment]
Following discussion
1) Make a copy of the vignette in spatialplanr (leave the GlobalFishingWatch repo as is)
2) Put your function in spatialplanr called splnr_get_gfw()

**Comment by KilianGRIHAULTBARREIRO** [comment]
So I thought I'd put that aside (the management of the `get_gfwData` function) while we think about whether or not to put it in the Utils or in an MME repository and concentrate on merging splnr_plotting.R.
